### ISSUE TITLE
difx2mark4 t309 PCal frequencies (DiFX-2.5.3 and later)

### ISSUE THREAD

**Issue by jwagnerhki** [difx/difx#43]
The t309 entries produced by difx2mark4 look a bit suspect. If I compared the entries correctly, the relative frequency offsets in the t309 data do not match the actual tone offsets in the baseband mk4 channels. This is in DiFX-2.5.3 and newer.

Traced it to a potential mix-up in array index. The complex pcal tone data are stored into `t309.chan[<channel idx>].acc[<accu idx>]` while the associated tone frequency offset in MHz is stored not in `t309.chan[<channel idx>].freq` but rather in `t309.chan[<accu idx>].freq`.

The access to the elements of t309.chan[].* is done like this in createType3s.c:

```
strcpy (t309.chan[ochan].chan_name, pfb[nf].stn[k].chan_id);
memcpy (&t309.chan[ochan].acc[i][0], &norm_corr, 4);
memcpy (&t309.chan[ochan].acc[i][1], &norm_corr, 4);
t309.chan[i].freq = 1e6 * f_rel;
```

cf. https://github.com/difx/difx/blob/main/applications/difx2mark4/src/createType3s.c#L1021

Compare that to write_t309.c where the access is

```
t309.chan[i].freq = ...
t309.chan[i].acc[j][0] = ...
t309.chan[i].acc[j][1] = ...
```

cf. https://github.com/difx/difx/blob/main/applications/difx2mark4/src/write_t309.c#L24

Hence I wonder whether createType3.c should actually use

```
t309.chan[ochan].freq = 1e6 * f_rel;
```

**Comment by jpbarrett** [comment]
I don't think this is necessarily a bug, it's just the way that Roger(?) defined the type_309s. They have a very convoluted and counterintuitive structure which I can only assume is due to the way the Mark4 correlator use to work. For example see the code in the function extract_pcal() in the file:

<hops3-repo>/chops/source/python_src/vpal_module/vpal/proxy_cable_cal.py

The value of the field 'freq' in the chan struct:

```
struct type_309
  {
  char        record_id[3];           // Standard 3-digit id
  char        version_no[2];          // Standard 2-digit version #
  char        unused1[3];
  int         su;                     // SU
  int         ntones;                 // number of tones [0..64]
  double      rot;                    // ROT at start of AP
  double      acc_period;             // in secs
  struct ch1_tag
    {
    char      chan_name[8];
    double    freq;                   // tone frequency in Hz
    U32       acc[64][2];             // accumulators for 64 freqs x 2 quads (C..S)
    } chan[64];
  };
```

corresponds to a frequency offset-from the channel edge of a tone stored at the some index n.

While at first glance this appears to mix up the index of the channel (chan) array and the tone accumulation (acc) array. The way that this is suppose to work, is that position of (a non-zero) tone in the acc array tells you the index n of where to look up the tone frequency.

Fourfit's code expects this, so I think this is how Roger intended it to be done. It is very convoluted and over complicated way to save a handful of bytes, when the struct could have just as easily stored the tone frequency alongside every tone.

In any case, this isn't going to be changed now, as we are moving away from the mark4 types.

**Comment by jwagnerhki** [comment]
Thanks for your comments and for looking into this! Not a bug then. I'll reference this (#43) from the "t309.chan[i].freq = ..." line to document the code.

**Comment by jwagnerhki** [comment]
Thanks for your comments and for looking into this! Not a bug then. I'll reference this (https://github.com/difx/difx/issues/43) from the "t309.chan[i].freq = ..." line to document the code.
